name: 'Automatic build for downloading feed'
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:   
  delete-old-rss-files:
    name: delete all friends feed files 
    runs-on: ubuntu-latest
    steps:
      - name: delete files
        run:
          rm -rf assets/friends_file/
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ./_friends_link
          git commit -a -m "Automatic delete rss files from workflow" || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: ${{ github.ref }}
          force: true
  
  download-feed-file-automatically:
    name: Update this feed files for friends
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wow-actions/download-upload@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          url: "https://tigercosmos.xyz/atom.xml"
          dir: assets/friends_file/
          filename: tigercosmos.xml
          
      - uses: wow-actions/download-upload@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          url: "https://blog.ryankert.cc/atom.xml"
          dir: assets/friends_file/
          filename: RyanKert.xml
          
      - uses: suisei-cn/actions-download-file@v1.3.0
        id: downloadfile  # Remember to give an ID if you need the output filename
        name: Download tigercosmos.xml
        with:
          url: "https://tigercosmos.xyz/atom.xml"
          target: assets/friends_file/
          filename: tigercosmos.xml
          
      - uses: suisei-cn/actions-download-file@v1.3.0
        name: Download RyanKert.xml
        with:
          url: "https://blog.ryankert.cc/atom.xml"
          target: assets/friends_file/
          filename: RyanKert.xml
          
  generate-md-file-for-rss:
    needs: download-feed-file-automatically
    name: transfer rss to markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: print directory
        run: ls -al
      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1 # Not needed with a .ruby-version file
      - name: install bundle
        run: bundle install
      - name: run feeds.rb
        run: ruby feeds.rb
        
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ./_friends_link
          git commit -a -m "Automatic add file from workflow" || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: ${{ github.ref }}
          force: true
        
