name: 'Automatic build for downloading feed'
on:
  push:
    branches: [ "main" ]
  schedule: # Run workflow automatically
    - cron: '0,15 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:   
  download-feed-file-automatically:
    name: Update this feed files for friends
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wow-actions/download-upload@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          url: "https://tigercosmos.xyz/atom.xml"
          dir: _friends_link/
          filename: tigercosmos.xml
          
      - uses: wow-actions/download-upload@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          url: "https://blog.ryankert.cc/atom.xml"
          dir: _friends_link/
          filename: RyanKert.xml
          
      - name: use feeds.rb to make rss to markdown
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: ruby feeds.rb
      
          
          
